/**
 * API-Footballは英語のクラブ名しか返さないため、日本語表示用の対応表を用意する。
 * 対象リーグ(config.pyのLEAGUES)の主要クラブを中心に収録。
 * 未収録のクラブは英語名のままフォールバック表示する。
 */
const TEAM_NAME_JA: Record<string, string> = {
  // プレミアリーグ
  Arsenal: "アーセナル",
  "Aston Villa": "アストン・ヴィラ",
  Bournemouth: "ボーンマス",
  Brentford: "ブレントフォード",
  Brighton: "ブライトン",
  Burnley: "バーンリー",
  Chelsea: "チェルシー",
  "Crystal Palace": "クリスタル・パレス",
  Everton: "エヴァートン",
  Fulham: "フラム",
  Liverpool: "リバプール",
  "Manchester City": "マンチェスター・シティ",
  "Manchester United": "マンチェスター・ユナイテッド",
  Newcastle: "ニューカッスル",
  "Nottingham Forest": "ノッティンガム・フォレスト",
  Sunderland: "サンダーランド",
  Tottenham: "トッテナム",
  "West Ham": "ウェストハム",
  Wolves: "ウォルバーハンプトン",

  // ラ・リーガ
  Alaves: "アラベス",
  "Athletic Club": "アスレティック・ビルバオ",
  "Atletico Madrid": "アトレティコ・マドリード",
  Barcelona: "バルセロナ",
  "Celta Vigo": "セルタ・ビーゴ",
  Elche: "エルチェ",
  Espanyol: "エスパニョール",
  Getafe: "ヘタフェ",
  Girona: "ジローナ",
  Levante: "レバンテ",
  Mallorca: "マヨルカ",
  Osasuna: "オサスナ",
  "Rayo Vallecano": "ラージョ・バジェカーノ",
  "Real Betis": "レアル・ベティス",
  "Real Madrid": "レアル・マドリード",
  "Real Oviedo": "レアル・オビエド",
  "Real Sociedad": "レアル・ソシエダ",
  Sevilla: "セビージャ",
  Valencia: "バレンシア",
  Villarreal: "ビジャレアル",

  // ブンデスリーガ
  Augsburg: "アウクスブルク",
  "Bayer Leverkusen": "バイエル・レバークーゼン",
  "Bayern Munich": "バイエルン・ミュンヘン",
  "Werder Bremen": "ヴェルダー・ブレーメン",
  "Borussia Dortmund": "ボルシア・ドルトムント",
  "Eintracht Frankfurt": "アイントラハト・フランクフルト",
  Freiburg: "フライブルク",
  Heidenheim: "ハイデンハイム",
  Hoffenheim: "ホッフェンハイム",
  "Union Berlin": "ウニオン・ベルリン",
  "RB Leipzig": "RBライプツィヒ",
  Mainz: "マインツ",
  "Borussia Monchengladbach": "ボルシア・メンヒェングラートバッハ",
  "St Pauli": "ザンクトパウリ",
  "FC Koln": "ケルン",
  "VfB Stuttgart": "シュツットガルト",
  Wolfsburg: "ヴォルフスブルク",
  "Hamburger SV": "ハンブルガーSV",

  // セリエA
  Atalanta: "アタランタ",
  Bologna: "ボローニャ",
  Cagliari: "カリアリ",
  Como: "コモ",
  Cremonese: "クレモネーゼ",
  Fiorentina: "フィオレンティーナ",
  Genoa: "ジェノア",
  "Hellas Verona": "エラス・ヴェローナ",
  Inter: "インテル",
  Juventus: "ユヴェントス",
  Lazio: "ラツィオ",
  Lecce: "レッチェ",
  "AC Milan": "ACミラン",
  Napoli: "ナポリ",
  Parma: "パルマ",
  Pisa: "ピサ",
  Roma: "ローマ",
  Sassuolo: "サッスオーロ",
  Torino: "トリノ",
  Udinese: "ウディネーゼ",

  // リーグ・アン
  Angers: "アンジェ",
  Auxerre: "オセール",
  Brest: "ブレスト",
  "Le Havre": "ル・アーヴル",
  Lens: "ランス",
  Lille: "リール",
  Lorient: "ロリアン",
  Lyon: "リヨン",
  Marseille: "マルセイユ",
  Metz: "メス",
  Monaco: "モナコ",
  Nantes: "ナント",
  Nice: "ニース",
  "Paris FC": "パリFC",
  "Paris Saint Germain": "パリ・サンジェルマン",
  Rennes: "レンヌ",
  Strasbourg: "ストラスブール",
  Toulouse: "トゥールーズ",

  // エールディヴィジ
  Ajax: "アヤックス",
  "AZ Alkmaar": "AZアルクマール",
  Feyenoord: "フェイエノールト",
  PSV: "PSVアイントホーフェン",
  "FC Twente": "FCトゥエンテ",
  "FC Utrecht": "FCユトレヒト",
  "Go Ahead Eagles": "ゴー・アヘッド・イーグルス",
  Groningen: "フローニンゲン",
  Heerenveen: "ヘーレンフェーン",
  "Fortuna Sittard": "フォルトゥナ・シッタルト",
  "NAC Breda": "NACブレダ",
  "NEC Nijmegen": "NECナイメヘン",
  "PEC Zwolle": "PECズヴォレ",
  "Sparta Rotterdam": "スパルタ・ロッテルダム",
  Volendam: "フォレンダム",

  // その他、日本人選手所属実績のあるクラブ
  Southampton: "サウサンプトン",
  "Stade Brestois 29": "ブレスト",

  // チャンピオンシップ(イングランド2部)
  "Coventry City": "コヴェントリー・シティ",
  "Stoke City": "ストーク・シティ",
  "Hull City": "ハル・シティ",
  "Blackburn Rovers": "ブラックバーン",
  "Birmingham City": "バーミンガム・シティ",
  Leeds: "リーズ・ユナイテッド",

  // スコットランド
  Rangers: "レンジャーズ",

  // ベルギー
  "Sint-Truiden": "シント＝トロイデン",
  Gent: "ゲント",

  // 日本人選手所属クラブ(対象11リーグ以外・上記の表記ゆれを含む)
  "1899 Hoffenheim": "ホッフェンハイム",
  Antwerp: "アントワープ",
  Arouca: "アロウカ",
  "Atlanta United FC": "アトランタ・ユナイテッド",
  Auckland: "オークランドFC",
  "Bayern München": "バイエルン・ミュンヘン",
  "Beerschot VA": "ベールスホット",
  Birmingham: "バーミンガム",
  Blackburn: "ブラックバーン",
  "Borussia Mönchengladbach": "ボルシア・メンヒェングラートバッハ",
  Brondby: "ブレンビーIF",
  Celtic: "セルティック",
  Coventry: "コヴェントリー",
  "DC United": "DCユナイテッド",
  "FC Basel 1893": "バーゼル",
  "FC Copenhagen": "コペンハーゲン",
  "FC Schalke 04": "シャルケ04",
  "FC St. Pauli": "ザンクトパウリ",
  "FSV Mainz 05": "マインツ",
  Genk: "ヘンク",
  "Hammarby FF": "ハンマルビー",
  "Hannover 96": "ハノーファー96",
  Ipswich: "イプスウィッチ",
  Jagiellonia: "ヤギェロニア・ビャウィストク",
  "KVC Westerlo": "ウェステルロー",
  Kortrijk: "コルトレイク",
  "Las Palmas": "ラス・パルマス",
  "Los Angeles Galaxy": "ロサンゼルス・ギャラクシー",
  "Melbourne City": "メルボルン・シティ",
  "OH Leuven": "OHルーヴェン",
  "PSV Eindhoven": "PSVアイントホーフェン",
  "Patro Eisden": "パトロ・アイスデン",
  "Queens Park Rangers": "クイーンズ・パーク・レンジャーズ",
  "Red Bull Salzburg": "レッドブル・ザルツブルク",
  Reims: "スタッド・ランス",
  "SC Freiburg": "フライブルク",
  "SCR Altach": "アルタッハ",
  "SV Darmstadt 98": "ダルムシュタット",
  Sintrense: "シント＝トロイデン",
  "Vancouver Whitecaps": "バンクーバー・ホワイトキャップス",
  "VfL Bochum": "ボーフム",
  "VfL Wolfsburg": "ヴォルフスブルク",
  "Wellington Phoenix": "ウェリントン・フェニックス",
  "Western Sydney Wanderers": "ウェスタン・シドニー・ワンダラーズ",

  // リーガ・ポルトガル(1部。国内カップ戦の下位アマチュアクラブは
  // 対戦相手が毎回変わり維持が非現実的なため対象外とする)
  Benfica: "ベンフィカ",
  "CF Benfica": "ベンフィカ",
  "SC Braga": "スポルティングCP・ブラガ",
  "Vitória SC": "ヴィトーリアSC",
  Moreirense: "モレイレンセ",
  Estoril: "エストリル",
  "GIL Vicente": "ジル・ヴィセンテ",
  Famalicao: "ファマリカオン",
  "Casa Pia": "カサ・ピア",
  Nacional: "ナシオナル",
  Estrela: "エストレーラ・アマドーラ",

  // スコティッシュ・プレミアシップ(未収録分)
  Aberdeen: "アバディーン",
  Hibernian: "ハイバーニアン",
  Motherwell: "マザーウェル",
  Dundee: "ダンディー",
  "ST Mirren": "セント・ミレン",

  // ベルギー・プロリーグ(未収録分)
  Anderlecht: "アンデルレヒト",
  "Club Brugge KV": "クラブ・ブルッヘ",
  "Union St. Gilloise": "ユニオン・サンジロワーズ",
  "Zulte Waregem": "ズルテ・ワレヘム",

  // スュペル・リグ(未収録分)
  Alanyaspor: "アラニヤスポル",
  "Fenerbahçe": "フェネルバフチェ",
  "Beşiktaş": "ベシクタシュ",
  Trabzonspor: "トラブゾンスポル",
  "Kasımpaşa": "カスンパシャ",
  Samsunspor: "サムスンスポル",
  Eyüpspor: "エユプスポル",
  "Başakşehir": "バシャクシェヒル",
  "Çorum FK": "チョルムFK",

  // エールディヴィジ(未収録分・オランダ杯の下部リーグ相手含む)
  Cambuur: "カンブール",
  Twente: "FCトゥエンテ",
  "Willem II": "ヴィレムII",
  Utrecht: "FCユトレヒト",
  "ADO Den Haag": "ADOデン・ハーグ",

  // その他、国内カップ戦で対象リーグクラブと対戦する主要クラブ
  Malaga: "マラガ",
  "Deportivo La Coruna": "デポルティボ・ラ・コルーニャ",
  "1. FC Kaiserslautern": "カイザースラウテルン",
  "AIK Stockholm": "AIKストックホルム",
  "AS Roma": "ローマ",
  "Austria Vienna": "アウストリア・ウィーン",
  "CF Os Belenenses": "オス・ベレネンセス",
  "FC Augsburg": "アウクスブルク",
  "FC Nordsjaelland": "ノアシェラン",
  "Le Mans": "ル・マン",
  "Raków Częstochowa": "ラコフ・チェンストホヴァ",
  "Sporting Kansas City": "スポルティング・カンザスシティ",
  "St. Truiden": "シント＝トロイデン",
  Telstar: "テルスター",
};

export function translateTeamName(name: string): string {
  return TEAM_NAME_JA[name] ?? name;
}
